spring:
  application:
    name: jpa
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: postgres
    password: '!ashe4321.'
  jpa:
      # 展示执行的sql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect